### ISSUE TITLE
Angular support?

### ISSUE THREAD

**Issue by AlexanderStromer** [teclone/industries#3]
1. npm install industries
2. import { industries } from "industries";

step 2 does not work with error being
Module '"<PID>/node_modules/industries/lib/typings"' has no exported member 'industries'. Did you mean 'Industries'?

**Comment by teclone** [comment]
Hello @AlexanderStromer, it is a default export, not named. use this method to import the inudstries

```javascript
import industries from 'industries';
```

Let me know if this solves it

**Comment by AlexanderStromer** [comment]
thx, solved! :)

I suggest to add to npm description for quickstart

**Comment by teclone** [comment]
I will do this later in the day. Thanks for your suggestions.
