### ISSUE TITLE
> I uploaded changes to remove build, cjs, esm, iiffe and umd directories before calling rollup-all. You could add this sequence in rollup-all and generate all the required directories inside of the build directory.

### ISSUE THREAD

**Issue by mastepanoski** [teclone/industries#35]
> I uploaded changes to remove build, cjs, esm, iiffe and umd directories before calling rollup-all. You could add this sequence in rollup-all and generate all the required directories inside of the build directory.

the latest version of rollup-all does this now, can you update to it?

_Originally posted by @teclone in https://github.com/teclone/industries/issues/34#issuecomment-1519016271_

When I updated the project (but I don´t push it yet). Then I ran yarn build, and I got:

node_modules/rollup/dist/shared/rollup.js:198
        base = Object.assign(new Error(base.message), base);
                             ^

Error: Invalid value for option "output.file" - when building multiple chunks, the "output.dir" option must be used, not "output.file". To inline dynamic imports, set the "inlineDynamicImports" option.
    at error (/node_modules/rollup/dist/shared/rollup.js:198:30)
    at validateOptionsForMultiChunkOutput (/node_modules/rollup/dist/shared/rollup.js:16078:16)
    at Bundle.generate (/node_modules/rollup/dist/shared/rollup.js:15910:17)
    at async /node_modules/rollup/dist/shared/rollup.js:23833:27
    at async catchUnfinishedHookActions (/node_modules/rollup/dist/shared/rollup.js:23247:20) {
  code: 'INVALID_OPTION',
  url: 'https://rollupjs.org/guide/en/#outputdir'
}

Node.js v18.15.0

**Comment by teclone** [comment]
@mastepanoski could you push the changes, i think the issue comes from the rollup.config.js file. you should change esm to es.
below is the content of rollup.config.js in the root file.

```javascript
const { createConfig } = require('@teclone/rollup-all');
module.exports = createConfig({
  formats: ['cjs', 'esm', 'iife', 'umd'],
  envs: ['uni'],
});
```

you should change esm to es. it was changed by the latest version of rollup-all

**Comment by mastepanoski** [comment]
Now it worked.
