### ISSUE TITLE
Consider multilingual

### ISSUE THREAD

**Issue by AlexanderStromer** [teclone/industries#4]
1. Maintain text multilingual
2. user provides language (e.g. en-us) and library fetches exact or partial match (e.g. en-us > en* > default); e.g. fetch request for (de-at will result in default language)
3. ids and textual-type can stay as is (as not exposed to UI)
4. linkedin (original source) might already provide translations into major languages (avoid self translating)

**Comment by teclone** [comment]
hello @AlexanderStromer , thank you for this feature request, it is a great one. I will look into this. but I think the best way to handle this would be that user imports what he needs, by himself.

for instance,
```javascript
import industriesInGerman from 'industries/de';
import industriesInFrench from 'industries/fr';
```

This way, bundlers such as webpack will be able to bundle in only what is needed, because of the way dynamic imports works

**Comment by teclone** [comment]
@AlexanderStromer  I have looked into google cloud translation api, We can make use of it, to run batch process, and perform translations, then create pull requests here

**Comment by AlexanderStromer** [comment]
The project node-i18n-iso-countries is doing something similar, contrary to the import statements above. I however prefer the import statements you suggested

node-i18n-iso-countries required me to do
1. import * as i18nIsoCountries from "i18n-iso-countries";
2. i18nIsoCountries.registerLocale(require("i18n-iso-countries/langs/en.json"));
3. var countryDictionary = i18nIsoCountries.getNames("en");

which I perceived not as straight forward and also not described on npm

**Comment by teclone** [comment]
yea, it is not that straight forward

**Comment by mastepanoski** [comment]
I created a pull request #31 related to this.

**Comment by teclone** [comment]
multilingual support now available. thanks to @mastepanoski
